# conda env create -f environment.yml && conda activate policy-checker && ./setup.sh
name: policy-checker
channels: [conda-forge]
dependencies:
  - python=3.10
  - openjdk>=17
  - numpy
  - pyparsing
  - pyyaml
  - pydantic
  - pip
  - pip:
      - jpype1
      - tarjan
      - anthropic
      - google-genai
      - pysmt
      - setuptools<80
